branch-defaults:
  default:
    environment: Mystore-env
deploy:
  artifact: www/Archive.zip
environment-defaults:
  Mystore-env:
    branch: null
    repository: null
global:
  application_name: mystore
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
